version: '3.7'

services:
  simulator:
    image: carlasim/carla:0.9.10.1
    container_name: carla-${USER}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true
    environment:
      SDL_VIDEODRIVER: dummy
      XAUTHORITY: ${XAUTHORITY:-$HOME/.Xauthority}
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    command: >
      bash -c "./CarlaUE4.sh -RenderOffScreen -nosound -benchmark -quality-level=Low -carla-rpc-port=5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/linshenghao/carla_data/:/home/carla/.config/Epic/CarlaUE4/Saved:rw

